### 1. Creating an array

In [1]:
import numpy as np

In [3]:
# np.array()
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [9]:
# np.zeros(), np.ones(), np.empty()
zeros_arr = np.zeros((3,3))
print(zeros_arr)
ones_arr = np.ones((2,2))
print(ones_arr)
empty_arr = np.empty((2,2))
print(empty_arr)
print(zeros_arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
(3, 3)


In [13]:
arr_1d = np.array(5)
print(arr_1d)
print(arr_1d.shape)

5
()


### 2. Array operation

##### a. Arithmatic Operations

In [16]:
# Pointwise Operations (Add, Sub, Mul, Div)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

addition =arr1+arr2
print("Addition: \n",addition)
subtraction = arr1-arr2
print("Subtraction: \n",subtraction)
multiplication = arr1 * arr2
print("Point wise multiplication: \n",multiplication)
division = arr1/arr2
print("Point wise division: \n", division)

Addition: 
 [[ 6  8]
 [10 12]]
Subtraction: 
 [[-4 -4]
 [-4 -4]]
Point wise multiplication: 
 [[ 5 12]
 [21 32]]
Point wise division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


##### b. Matrix Multiplication

In [17]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

matrix_multiply = np.dot(arr1,arr2)
print("Matrix multiplication: \n",matrix_multiply)

Matrix multiplication: 
 [[19 22]
 [43 50]]


##### c. Transpose of matrix

In [18]:
transposed_arr = arr1.T
print("transposed matrix: ", transposed_arr)

transposed matrix:  [[1 3]
 [2 4]]


### 3. Universal Functions(ufuncs)

##### a. np.sum(), np.mean(), np.std(), np.min(), np.max()

In [20]:
arr1 = np.array([[1,2],[3,4]])

total = np.sum(arr1)
average = np.mean(arr1)
standard_deviation = np.std(arr1)
minimum_value = np.min(arr1)
maximum_value = np.max(arr1)

print(f"Total: {total}\n, Average: {average}\n, STD deviation: {standard_deviation}\n, Min value: {minimum_value}, Max Value: {maximum_value}")

Total: 10
, Average: 2.5
, STD deviation: 1.118033988749895
, Min value: 1, Max Value: 4


### 4. Array Manipulation

##### a. Reshaping

In [21]:
arr = np.array([1,2,3,4])
print(arr.shape)
reshaped_arr = arr.reshape((2,2))
print(reshaped_arr.shape)

(4,)
(2, 2)


##### b. Flattening

In [23]:
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)

[1 2 3 4]


### 5. Indexing and slicing

In [26]:
l = [i for i in range(16)]
arr = np.array(l)
print(arr)
reshaped_arr = arr.reshape((4,4))
print(reshaped_arr)
subset = reshaped_arr[1:3,0:2]
print(subset)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[4 5]
 [8 9]]


### 6. Broadcasting

In [28]:
# NumPy performs broadcasting when performing operations on arrays of different shapes.
# Broadcasting is applying same operation to all the elements
arr1 = np.array([1, 2, 3])
arr2 = 2

result = arr1 + arr2
result

array([3, 4, 5])

### 7. Random Module

In [29]:
random_arr = np.random.rand(3,3) # uniform distribution
print(random_arr)

[[0.78695873 0.68891677 0.08227426]
 [0.91877707 0.5124185  0.6263693 ]
 [0.49237842 0.25410694 0.19969274]]


### 8. Linear Algebra

In [31]:
eigenvalues, eigenvectors = np.linalg.eig(random_arr)
print(eigenvalues)
print(eigenvectors)

[ 1.61918183+0.j         -0.06005593+0.14480625j -0.06005593-0.14480625j]
[[ 0.61915889+0.j         -0.56875632-0.13183234j -0.56875632+0.13183234j]
 [ 0.7071869 +0.j          0.70422193+0.j          0.70422193-0.j        ]
 [ 0.34136337+0.j          0.19064027+0.35618008j  0.19064027-0.35618008j]]


# Vectors

##### 1.Dot Product

In [33]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

dot_product = np.dot(vector1, vector2)
print("Dot Product:", dot_product)

Dot Product: 32


##### 2. Cross Product

In [34]:
cross_product = np.cross(vector1, vector2)
print("Cross Product:", cross_product)

Cross Product: [-3  6 -3]


##### 3. Magnitude of a vector

In [36]:
magnitude = np.linalg.norm(vector1)
print("Magnitude:", magnitude)

Magnitude: 3.7416573867739413


##### 4. Unit vector

In [38]:
unit_vector = vector1/ np.linalg.norm(vector1)
print("Unit Vector:", unit_vector)

Unit Vector: [0.26726124 0.53452248 0.80178373]


##### 5.Angle between vectors 

In [39]:
cosine_similarity = np.dot(vector1, vector2)/(np.linalg.norm(vector1) * np.linalg.norm(vector2))
angle_radians = np.arccos(cosine_similarity)
angle_degrees = np.degrees(angle_radians)
print("Angle (degrees):", angle_degrees)

Angle (degrees): 12.933154491899135


##### 6. Projection of a vector onto another 

In [40]:
projection = np.dot(vector1,vector2)/ np.linalg.norm(vector2) * (vector2/np.linalg.norm(vector2))
print("Projection:", projection)

Projection: [1.66233766 2.07792208 2.49350649]


##### 7. Element-wise Operation

In [41]:
elementwise_sum = vector1 + vector2
elementwise_difference = vector1 - vector2
elementwise_multiplication = vector1 * vector2
elementwise_division = vector1 / vector2

print("Element-wise Sum:", elementwise_sum)
print("Element-wise Difference:", elementwise_difference)
print("Element-wise Multiplication:", elementwise_multiplication)
print("Element-wise Division:", elementwise_division)

Element-wise Sum: [5 7 9]
Element-wise Difference: [-3 -3 -3]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]


##### 8. Vector Stacking

In [42]:
stacked_vector = np.vstack((vector1,vector2)) #vertically stacked
print("Vertically Stacked Vector:\n", stacked_vector)

Vertically Stacked Vector:
 [[1 2 3]
 [4 5 6]]


##### 9. Element-wise Functions

In [44]:
sin_vector = np.sin(vector1)
cos_vector = np.cos(vector1)
exp_vector = np.exp(vector1)

print("Sin Vector:", sin_vector)
print("Cos Vector:", cos_vector)
print("Exponential Vector:", exp_vector)

Sin Vector: [0.84147098 0.90929743 0.14112001]
Cos Vector: [ 0.54030231 -0.41614684 -0.9899925 ]
Exponential Vector: [ 2.71828183  7.3890561  20.08553692]


##### 10. Vector Comparison

In [45]:
vector_comparison=(vector1>vector2)
print("Vector Comparison (element-wise greater than):", vector_comparison)

Vector Comparison (element-wise greater than): [False False False]


##### 11. Cummulative sum

In [46]:
cumulative_sum = np.cumsum(vector1)
print("Cumulative Sum:", cumulative_sum)

Cumulative Sum: [1 3 6]


##### 12. Sorting

In [47]:
sorted_vector =np.sort(vector1)
print("Sorted Vector:", sorted_vector)

Sorted Vector: [1 2 3]


# Linear Algebra

##### 1. Matrix Inversion

In [49]:
matrix = np.array([[1,2],[3,4]])
print(matrix)
inverse_matrix = np.linalg.inv(matrix)
print("Inverse Matrix: \n", inverse_matrix)

[[1 2]
 [3 4]]
Inverse Matrix: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


##### 2. Solving linear equation

In [52]:
coefficients = np.array([[2,3],[1,-2]])
constants = np.array([8,-4])

solution = np.linalg.solve(coefficients, constants)
print("Solution to the linear equations: ",solution)

Solution to the linear equations:  [0.57142857 2.28571429]


##### 3. Determinant of a matrix

In [53]:
determinant = np.linalg.det(matrix)
print("Determinant of the matrix: ",determinant)

Determinant of the matrix:  -2.0000000000000004


##### 4. Eigen Value and Eigen Vector

In [54]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


##### 5. Singular value decomposition (SVD)

In [56]:
matrix = np.array([[1,2],[3,4]])
U,S,V = np.linalg.svd(matrix)
print("U matrix:\n", U)
print("S matrix:\n", S)
print("V matrix:\n", V)

U matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S matrix:
 [5.4649857  0.36596619]
V matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


##### 6. Boolean Indexing

In [57]:
array = np.array([1,2,3,4,5])
mask = array>2
filtered_array =array[mask]
print("Filtered Array: ", filtered_array)

Filtered Array:  [3 4 5]


##### 7. Statistical operation

In [58]:
mean_value = np.mean(array)
median_value = np.median(array)
std_deviation = np.std(array)

##### 8. Concatenation

In [59]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenated_array = np.concatenate((array1, array2))
print("Concatenated Array:", concatenated_array)

Concatenated Array: [1 2 3 4 5 6]


##### 9. Unique Elements and Counts

In [60]:
unique_elements, counts = np.unique(array, return_counts=True)
print("unique elements: ", unique_elements)
print("Counts: ", counts)

unique elements:  [1 2 3 4 5]
Counts:  [1 1 1 1 1]


##### 10. Loading and Saving data

In [ ]:
np.savetxt('data.txt', array, delimiter=',')
loaded_data = np.loadtxt('data.txt', delimiter=',')
print("Loaded Data:", loaded_data)

# Other Operations

##### 1. Masked Arrays

In [61]:
import numpy.ma as ma

masked_array = ma.masked_where(array < 3, array)
print("Masked Array:", masked_array)

Masked Array: [-- -- 3 4 5]


##### 2. Polynomials

In [62]:
coefficients = [1, -2, 1]  # Represents x^2 - 2x + 1
polynomial = np.poly1d(coefficients)
roots = np.roots(coefficients)
print("Polynomial:", polynomial)
print("Roots of the Polynomial:", roots)

Polynomial:    2
1 x - 2 x + 1
Roots of the Polynomial: [1.+6.68896751e-09j 1.-6.68896751e-09j]


##### 3. Interpolation

In [63]:
from scipy.interpolate import interp1d

x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 2, 1, 3, 4])

interp_function = interp1d(x, y, kind='linear')
new_x = np.linspace(0, 4, 10)
interpolated_values = interp_function(new_x)
print("Interpolated Values:", interpolated_values)

Interpolated Values: [0.         0.88888889 1.77777778 1.66666667 1.22222222 1.44444444
 2.33333333 3.11111111 3.55555556 4.        ]


##### 4. Fourier Transform

In [64]:
signal = np.array([1, 2, 1, -1, 1.5])
fourier_transform = np.fft.fft(signal)
print("Fourier Transform of Signal:", fourier_transform)

Fourier Transform of Signal: [ 4.5       +0.j          2.08155948-1.65109876j -1.83155948+1.60822041j
 -1.83155948-1.60822041j  2.08155948+1.65109876j]


##### 5. Histogram 

In [65]:
data = np.random.randn(1000)
hist, edges = np.histogram(data, bins=10)
print("Histogram:", hist)
print("Bin Edges:", edges)

Histogram: [  4  15  60 139 233 227 183  97  36   6]
Bin Edges: [-3.22558263 -2.61228217 -1.99898171 -1.38568124 -0.77238078 -0.15908031
  0.45422015  1.06752061  1.68082108  2.29412154  2.907422  ]


##### 6. Random Sampling

In [66]:
random_uniform = np.random.uniform(low=0, high=1, size=5)
random_normal = np.random.normal(loc=0, scale=1, size=5)
print("Random Uniform:", random_uniform)
print("Random Normal:", random_normal)

Random Uniform: [0.02809389 0.87119913 0.45131436 0.15154473 0.19559658]
Random Normal: [ 1.70925749  0.61606557 -0.02493951 -0.39188537 -0.19843772]


##### 7. Vectorized String Operations

In [68]:
strings = np.array(['apple', 'banana', 'cherry'])
uppercase_strings = np.char.upper(strings)
print("Uppercase Strings:", uppercase_strings)

Uppercase Strings: ['APPLE' 'BANANA' 'CHERRY']


##### 8.  Cartesian Product

In [70]:
array1 = np.array([1, 2])
array2 = np.array(['a', 'b'])
cartesian_product = np.cartesian((array1, array2))
print("Cartesian Product:", cartesian_product)

AttributeError: module 'numpy' has no attribute 'cartesian'

##### 9. Vectorized Function

In [71]:
original_array = np.array([1, 2, 3])
squared_array = np.vectorize(lambda x: x**2)(original_array)
print("Squared Array:", squared_array)

Squared Array: [1 4 9]


##### 10. Ravel

In [72]:
multi_dim_array = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = multi_dim_array.ravel()
print("Flattened Array:", flattened_array)

Flattened Array: [1 2 3 4 5 6]


##### 11. Stacking

In [73]:
stacked_horizontal = np.hstack((array1, array2))
stacked_vertical = np.vstack((array1, array2))
print("Stacked Horizontally:", stacked_horizontal)
print("Stacked Vertically:", stacked_vertical)

Stacked Horizontally: ['1' '2' 'a' 'b']
Stacked Vertically: [['1' '2']
 ['a' 'b']]


##### 12. Splitting

In [75]:
array = np.array([1, 2, 1, -1, 1.5])
split_arrays = np.split(array, 2)
print("Split Arrays:", split_arrays)

ValueError: array split does not result in an equal division

##### 13. Repeat and Tile

In [77]:
array = np.array([1,2,3,4,5])
repeated_array = np.repeat(array, 3)
tiled_array = np.tile(array, 2)
print("Repeated Array:", repeated_array)
print("Tiled Array:", tiled_array)

Repeated Array: [1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]
Tiled Array: [1 2 3 4 5 1 2 3 4 5]


##### 14. Search Sorted

In [79]:
sorted_array = np.sort(array)
indices = np.searchsorted(sorted_array, 2)
print("Indices:", indices)

Indices: 1


##### 15. Gradient

In [80]:
gradient = np.gradient(array)
print("Gradient:", gradient)

Gradient: [1. 1. 1. 1. 1.]


##### 16. Histogram2d

In [82]:
x = np.random.randn(100)
y = np.random.randn(100)
histogram, x_edges, y_edges = np.histogram2d(x, y, bins=(5, 5))
print("2D Histogram:", histogram)
print("X Edges:", x_edges)
print("Y Edges:", y_edges)

2D Histogram: [[ 0.  1.  0.  2.  0.]
 [ 2.  8. 11. 10.  2.]
 [ 1.  6. 20.  9. 11.]
 [ 1.  3.  4.  3.  3.]
 [ 0.  1.  1.  0.  1.]]
X Edges: [-2.72845069 -1.55517501 -0.38189934  0.79137633  1.96465201  3.13792768]
Y Edges: [-2.60457229 -1.69774037 -0.79090845  0.11592347  1.02275539  1.92958732]


##### 17. Broadcasting

In [83]:
array1 = np.array([1, 2, 3])
scalar = 2
result = array1 + scalar
print("Broadcasting Result:", result)


Broadcasting Result: [3 4 5]
